version: "3"
services:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - spitify-pgsql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      placement:
        constraints: [ node.role == manager ]

volumes:
  spitify-pgsql:
